# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 499)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1071, 249))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelSelectPoint = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSelectPoint.sizePolicy().hasHeightForWidth())
        self.labelSelectPoint.setSizePolicy(sizePolicy)
        self.labelSelectPoint.setText("")
        self.labelSelectPoint.setObjectName("labelSelectPoint")
        self.horizontalLayout_5.addWidget(self.labelSelectPoint)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnUpdate = QtWidgets.QPushButton(self.centralWidget)
        self.btnUpdate.setEnabled(False)
        self.btnUpdate.setObjectName("btnUpdate")
        self.horizontalLayout_2.addWidget(self.btnUpdate)
        self.labelPageNum = QtWidgets.QLabel(self.centralWidget)
        self.labelPageNum.setText("")
        self.labelPageNum.setObjectName("labelPageNum")
        self.horizontalLayout_2.addWidget(self.labelPageNum)
        self.btnPrevious = QtWidgets.QPushButton(self.centralWidget)
        self.btnPrevious.setEnabled(False)
        self.btnPrevious.setObjectName("btnPrevious")
        self.horizontalLayout_2.addWidget(self.btnPrevious)
        self.btnNext = QtWidgets.QPushButton(self.centralWidget)
        self.btnNext.setEnabled(False)
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_2.addWidget(self.btnNext)
        self.btnZoomIn = QtWidgets.QPushButton(self.centralWidget)
        self.btnZoomIn.setObjectName("btnZoomIn")
        self.horizontalLayout_2.addWidget(self.btnZoomIn)
        self.btnZoomOut = QtWidgets.QPushButton(self.centralWidget)
        self.btnZoomOut.setObjectName("btnZoomOut")
        self.horizontalLayout_2.addWidget(self.btnZoomOut)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnAutoDetect = QtWidgets.QPushButton(self.centralWidget)
        self.btnAutoDetect.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAutoDetect.sizePolicy().hasHeightForWidth())
        self.btnAutoDetect.setSizePolicy(sizePolicy)
        self.btnAutoDetect.setObjectName("btnAutoDetect")
        self.horizontalLayout_3.addWidget(self.btnAutoDetect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spbPagesPerSheet = QtWidgets.QSpinBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spbPagesPerSheet.sizePolicy().hasHeightForWidth())
        self.spbPagesPerSheet.setSizePolicy(sizePolicy)
        self.spbPagesPerSheet.setMinimum(1)
        self.spbPagesPerSheet.setMaximum(6)
        self.spbPagesPerSheet.setProperty("value", 6)
        self.spbPagesPerSheet.setObjectName("spbPagesPerSheet")
        self.horizontalLayout_3.addWidget(self.spbPagesPerSheet)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.labelWidthHeight = QtWidgets.QLabel(self.centralWidget)
        self.labelWidthHeight.setObjectName("labelWidthHeight")
        self.horizontalLayout_3.addWidget(self.labelWidthHeight)
        self.spbWidth = QtWidgets.QSpinBox(self.centralWidget)
        self.spbWidth.setMaximum(9999)
        self.spbWidth.setObjectName("spbWidth")
        self.horizontalLayout_3.addWidget(self.spbWidth)
        self.spbHeight = QtWidgets.QSpinBox(self.centralWidget)
        self.spbHeight.setMaximum(9999)
        self.spbHeight.setObjectName("spbHeight")
        self.horizontalLayout_3.addWidget(self.spbHeight)
        self.btnWidthHeight = QtWidgets.QPushButton(self.centralWidget)
        self.btnWidthHeight.setObjectName("btnWidthHeight")
        self.horizontalLayout_3.addWidget(self.btnWidthHeight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelPageOne = QtWidgets.QLabel(self.centralWidget)
        self.labelPageOne.setObjectName("labelPageOne")
        self.horizontalLayout_4.addWidget(self.labelPageOne)
        self.spbPage1X = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage1X.setMaximum(9999)
        self.spbPage1X.setObjectName("spbPage1X")
        self.horizontalLayout_4.addWidget(self.spbPage1X)
        self.spbPage1Y = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage1Y.setMaximum(9999)
        self.spbPage1Y.setObjectName("spbPage1Y")
        self.horizontalLayout_4.addWidget(self.spbPage1Y)
        self.btnPageOne = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageOne.setObjectName("btnPageOne")
        self.horizontalLayout_4.addWidget(self.btnPageOne)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.labelPageTwo = QtWidgets.QLabel(self.centralWidget)
        self.labelPageTwo.setObjectName("labelPageTwo")
        self.horizontalLayout_4.addWidget(self.labelPageTwo)
        self.spbPage2X = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage2X.setMaximum(9999)
        self.spbPage2X.setObjectName("spbPage2X")
        self.horizontalLayout_4.addWidget(self.spbPage2X)
        self.spbPage2Y = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage2Y.setMaximum(9999)
        self.spbPage2Y.setObjectName("spbPage2Y")
        self.horizontalLayout_4.addWidget(self.spbPage2Y)
        self.btnPageTwo = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageTwo.setObjectName("btnPageTwo")
        self.horizontalLayout_4.addWidget(self.btnPageTwo)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.labelPageThree = QtWidgets.QLabel(self.centralWidget)
        self.labelPageThree.setObjectName("labelPageThree")
        self.horizontalLayout_4.addWidget(self.labelPageThree)
        self.spbPage3X = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage3X.setMaximum(9999)
        self.spbPage3X.setObjectName("spbPage3X")
        self.horizontalLayout_4.addWidget(self.spbPage3X)
        self.spbPage3Y = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage3Y.setMaximum(9999)
        self.spbPage3Y.setObjectName("spbPage3Y")
        self.horizontalLayout_4.addWidget(self.spbPage3Y)
        self.btnPageThree = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageThree.setObjectName("btnPageThree")
        self.horizontalLayout_4.addWidget(self.btnPageThree)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelPageFour = QtWidgets.QLabel(self.centralWidget)
        self.labelPageFour.setObjectName("labelPageFour")
        self.horizontalLayout_6.addWidget(self.labelPageFour)
        self.spbPage4X = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage4X.setMaximum(9999)
        self.spbPage4X.setObjectName("spbPage4X")
        self.horizontalLayout_6.addWidget(self.spbPage4X)
        self.spbPage4Y = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage4Y.setMaximum(9999)
        self.spbPage4Y.setObjectName("spbPage4Y")
        self.horizontalLayout_6.addWidget(self.spbPage4Y)
        self.btnPageFour = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageFour.setObjectName("btnPageFour")
        self.horizontalLayout_6.addWidget(self.btnPageFour)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.labelPageFive = QtWidgets.QLabel(self.centralWidget)
        self.labelPageFive.setObjectName("labelPageFive")
        self.horizontalLayout_6.addWidget(self.labelPageFive)
        self.spbPage5X = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage5X.setMaximum(9999)
        self.spbPage5X.setObjectName("spbPage5X")
        self.horizontalLayout_6.addWidget(self.spbPage5X)
        self.spbPage5Y = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage5Y.setMaximum(9999)
        self.spbPage5Y.setObjectName("spbPage5Y")
        self.horizontalLayout_6.addWidget(self.spbPage5Y)
        self.btnPageFive = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageFive.setObjectName("btnPageFive")
        self.horizontalLayout_6.addWidget(self.btnPageFive)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.labelPageSix = QtWidgets.QLabel(self.centralWidget)
        self.labelPageSix.setObjectName("labelPageSix")
        self.horizontalLayout_6.addWidget(self.labelPageSix)
        self.spbPage6X = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage6X.setMaximum(9999)
        self.spbPage6X.setObjectName("spbPage6X")
        self.horizontalLayout_6.addWidget(self.spbPage6X)
        self.spbPage6Y = QtWidgets.QSpinBox(self.centralWidget)
        self.spbPage6Y.setMaximum(9999)
        self.spbPage6Y.setObjectName("spbPage6Y")
        self.horizontalLayout_6.addWidget(self.spbPage6Y)
        self.btnPageSix = QtWidgets.QPushButton(self.centralWidget)
        self.btnPageSix.setObjectName("btnPageSix")
        self.horizontalLayout_6.addWidget(self.btnPageSix)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1091, 32))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Convert = QtWidgets.QAction(MainWindow)
        self.action_Convert.setObjectName("action_Convert")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Convert)
        self.menu_Help.addAction(self.actionAbout_Qt)
        self.menu_Help.addAction(self.action_About)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PdfHandoutCrop"))
        self.btnUpdate.setText(_translate("MainWindow", "&Update"))
        self.btnPrevious.setText(_translate("MainWindow", "&Previous"))
        self.btnNext.setText(_translate("MainWindow", "&Next"))
        self.btnZoomIn.setText(_translate("MainWindow", "Zoom &in"))
        self.btnZoomOut.setText(_translate("MainWindow", "Zoom &out"))
        self.btnAutoDetect.setText(_translate("MainWindow", "&Auto detect"))
        self.label.setText(_translate("MainWindow", "Pages per sheet:"))
        self.labelWidthHeight.setText(_translate("MainWindow", "Width and Height"))
        self.btnWidthHeight.setText(_translate("MainWindow", "Set"))
        self.labelPageOne.setText(_translate("MainWindow", "Page 1"))
        self.btnPageOne.setText(_translate("MainWindow", "Set"))
        self.labelPageTwo.setText(_translate("MainWindow", "Page 2"))
        self.btnPageTwo.setText(_translate("MainWindow", "Set"))
        self.labelPageThree.setText(_translate("MainWindow", "Page 3"))
        self.btnPageThree.setText(_translate("MainWindow", "Set"))
        self.labelPageFour.setText(_translate("MainWindow", "Page 4"))
        self.btnPageFour.setText(_translate("MainWindow", "Set"))
        self.labelPageFive.setText(_translate("MainWindow", "Page 5"))
        self.btnPageFive.setText(_translate("MainWindow", "Set"))
        self.labelPageSix.setText(_translate("MainWindow", "Page 6"))
        self.btnPageSix.setText(_translate("MainWindow", "Set"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Convert.setText(_translate("MainWindow", "&Convert"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About &Qt"))
        self.action_About.setText(_translate("MainWindow", "&About"))

